name: "Check EditorConfig"

permissions: read-all

on:
  push:
    branches: [master]
  pull_request:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v24
    - name: "Check EditorConfig"
      # Python already has Ruff,
      # and doesn't necessarily have a consistent 4 spaces indent
      run: nix run 'nixpkgs#eclint' --inputs-from . -- -show_all_errors -exclude "**/*.py"
