name: "Release artifacts"

permissions: read-all

on:
  # Allows running this workflow manually
  workflow_dispatch:
  push:
    tags:
      - "v*.*"

jobs:
  appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v24
      - uses: DeterminateSystems/magic-nix-cache-action@v2
        with:
          diagnostic-endpoint: ""
      - name: Build AppImage
        id: build-appimage
        run: |
          nix build -L '.#AppImage'
          result_path="$(realpath result)"
          cp --dereference result "${result_path#*-}"
      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: |
            *.AppImage
